### ISSUE TITLE
overwrite without asking

### ISSUE THREAD

**Issue by mojtabye** [FGRibreau/node-amqp-tool#20]
this command will overwrites data and destroy data without asking!
this should fix by asking are you sure to overwrite file?
`amqp-tool --host localhost -u user -p pass -q queue --export data.json`

**Comment by FGRibreau** [comment]
No need, just respect Unix principles:

```
amqp-tool --host localhost -u user -p pass -q queue --export > /tmp/data.json && cp -i /tmp/data.json data.json
```

`cp -i` will ask you if you want to overwrite the file only if it already exists
