### ISSUE TITLE
export message to multiple files

### ISSUE THREAD

**Issue by mojtabye** [FGRibreau/node-amqp-tool#21]
adding an ability to export a queue with millions of messages to multiple files with specific message count gonna help!

amqp-tool --host localhost -u user -p pass -q queue --count 500 --read 20000000 --export data.json

**Comment by FGRibreau** [comment]
No need, just respect Unix principles, see https://unix.stackexchange.com/a/26176 :)

```
amqp-tool --host localhost -u user -p pass -q queue --count 500 --read 20000000 --export | split -l 1000 -
```
